<a href="https://colab.research.google.com/github/tsangrebecca/BloomTech/blob/main/Sprint2/Module2/O3_UseAChi_SquareTestP_ValueToDrawTheCorrectConclusionAboutTheNullAndAlternativeHypothesis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Remember:
p-value < alpha to reject the null hypothesis
p-value > alpha to fail to reject the null hypothesis, we can't say to accept

In [1]:
import numpy as np

# create the array for dice roll, for each die value
a1 = [13, 7, 10, 5, 13]
a2 = [5, 7, 4, 12, 9]
a3 = [5, 9, 14, 0, 10]
a4 = [12, 13, 8, 7, 7]
a5 = [7, 10, 9, 13, 6]
a6 = [8, 4, 5, 13, 5]

# combine them into a (6,5) array
dice = np.array([a1, a2, a3, a4, a5, a6])
dice

array([[13,  7, 10,  5, 13],
       [ 5,  7,  4, 12,  9],
       [ 5,  9, 14,  0, 10],
       [12, 13,  8,  7,  7],
       [ 7, 10,  9, 13,  6],
       [ 8,  4,  5, 13,  5]])

In [2]:
# import the stats module
from scipy.stats import chi2_contingency

# perform the chi-square test
stat, p, dof, expected = chi2_contingency(dice, correction = False)

# print out the stats in a nice format
print('Expected values: \n ', expected.round(2))
print('The degrees of freedom: ', dof)
print(f'The chi square statistics is: {stat:.3f}')
print(f'The p value is: {p:.6f}')

Expected values: 
  [[9.6 9.6 9.6 9.6 9.6]
 [7.4 7.4 7.4 7.4 7.4]
 [7.6 7.6 7.6 7.6 7.6]
 [9.4 9.4 9.4 9.4 9.4]
 [9.  9.  9.  9.  9. ]
 [7.  7.  7.  7.  7. ]]
The degrees of freedom:  20
The chi square statistics is: 40.375
The p value is: 0.004477


In [4]:
# alplha level is 0.05, dof = (6-1)*(5-1) = 20, chi-square critical value is 31.410. calculated chi-square value is 40.375 > 31.410, larger than the critical value, which means
#  our results are not due to chance, that there is some significance.
# p-value is 0.004 < 0.05, which means we can reject our null hypothesis that the die is fair, and can conclude that the computer die is rigged!

In [5]:
# another example

# Create the array for each die value
a1 = [4, 3, 5, 11, 4]
a2 = [9, 15, 10, 4, 11]
a3 = [7, 10, 8, 6, 8 ]
a4 = [13, 6, 8, 9, 12]
a5 = [9, 9, 7, 11, 6]
a6 = [8, 7, 12, 9, 9]

# Combine them into a (6,5) array
dice = np.array([a1, a2, a3, a4, a5, a6])

In [6]:
# Perform the chi-square test
stat, p, dof, expected = chi2_contingency(dice, correction=False)

# Print out the stats in a nice format
print('Expected values: \n ', expected.round(2))
print(f'The chi square statistics is: {stat:.3f}')
print(f'The p value is: {p:.6f}')

Expected values: 
  [[5.4 5.4 5.4 5.4 5.4]
 [9.8 9.8 9.8 9.8 9.8]
 [7.8 7.8 7.8 7.8 7.8]
 [9.6 9.6 9.6 9.6 9.6]
 [8.4 8.4 8.4 8.4 8.4]
 [9.  9.  9.  9.  9. ]]
The chi square statistics is: 21.989
The p value is: 0.341086


In [ ]:
# in this case, the chi-square < than critical value of 31.41, and the p-value of 0.34 > 0.05, so in this case we fail to reject the null hypothesis
# then we can conclude that our results are what we would expect if the physical dice used were fair.

In [ ]:
# If we have two arrays of categorical values, we have to use this code to produce a contingency table
pd.crosstab(variable1, variable2, margins=True) # we need to write margins=True to display the row and column totals